export type AuditLog = {
    id: number;
    user_id: number | null;
    user_name: string | null;
    user_email: string | null;
    action: string;
    model_type: string | null;
    model_id: number | null;
    old_values: Array<any> | null;
    new_values: Array<any> | null;
    ip_address: string | null;
    user_agent: string | null;
    created_at: string;
    updated_at: string;
    model_name: string | null;
};
export type AuthUser = {
    id: number;
    name: string;
    email: string;
    role: UserRole;
    avatar: string | null;
    created_at: string;
    updated_at: string;
};
export type Company = {
    id: number;
    name: string;
    email: string | null;
    phone: string | null;
    logo: string | null;
    description: string | null;
    address: string | null;
    latitude: number | null;
    longitude: number | null;
    radius_meters: number | null;
    created_at: string;
    updated_at: string;
};
export type DailySchedule = {
    id: number;
    day_of_week: string;
    start_time: string | null;
    end_time: string | null;
    break_duration: number | null;
    is_working_day: boolean;
    created_at: string;
    updated_at: string;
};
export type LeaveRequest = {
    id: number;
    user_id: number;
    type: LeaveRequestType;
    start_date: string;
    end_date: string;
    reason: string | null;
    status: LeaveRequestStatus;
    processed_by_manager_id: number | null;
    manager_comment: string | null;
    created_at: string;
    updated_at: string;
    user: UserBasic | null;
    manager: UserBasic | null;
};
export type LeaveRequestStatus = 'pending' | 'approved' | 'rejected';
export type LeaveRequestType = 'sick' | 'vacation' | 'unpaid' | 'personal';
export type Message = {
    id: number;
    sender_id: number;
    receiver_id: number;
    message: string;
    created_at: string;
    sender: UserBasic | null;
    receiver: UserBasic | null;
};
export type TimeEntry = {
    id: number;
    user_id: number;
    start_time: string;
    stop_time: string | null;
    duration: number | null;
    entry_type: string | null;
    location_data: Array<any> | null;
    start_comment: string | null;
    stop_comment: string | null;
    created_at: string;
    updated_at: string;
    user: UserBasic | null;
};
export type TimeEntrySummary = {
    user_id: number;
    total_hours: number;
    total_minutes: number;
    entries_count: number;
    average_work_time: number;
    summary: TimeEntrySummaryPeriod;
};
export type TimeEntrySummaryPeriod = {
    today: number;
    week: number;
    month: number;
};
export type User = {
    id: number;
    name: string;
    email: string;
    role: UserRole;
    company_id: number | null;
    manager_id: number | null;
    avatar: string | null;
    work_schedule_id: number | null;
    work_mode: WorkMode;
    pin_code: string | null;
    created_at: string;
    updated_at: string;
    has_pin_code: boolean;
    company: Company | null;
    manager: UserBasic | null;
    work_schedule: WorkSchedule | null;
};
export type UserBasic = {
    id: number;
    name: string;
    email: string;
    avatar: string | null;
};
export type UserRole = 'employee' | 'admin' | 'manager';
export type WorkMode = 'remote' | 'office' | 'hybrid';
export type WorkSchedule = {
    id: number;
    name: string;
    description: string | null;
    is_default: boolean;
    company_id: number;
    created_at: string;
    updated_at: string;
    daily_schedules: Array<DailySchedule>;
};
